// This file is intentionally left blank.
// The firebase config will be populated by the backend.
// DO NOT EDIT THIS FILE.
import { FirebaseOptions, initializeApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "placeholder",
  authDomain: "placeholder",
  projectId: "placeholder",
  storageBucket: "placeholder",
  messagingSenderId: "placeholder",
  appId: "placeholder"
};

function getFirebaseConfig() {
    // This is a placeholder for the actual Firebase config.
    // The backend will replace this with the real config.
    // This is to allow the app to build without a config.
    if (!firebaseConfig || !firebaseConfig.apiKey || firebaseConfig.apiKey === 'placeholder') {
        return null;
    }
    return firebaseConfig;
}

// Initialize Firebase
const app = initializeApp(getFirebaseConfig()!);

export { app, getFirebaseConfig };
